-- Meridian Freight Solutions nightly export
-- Generated by scheduled job mfs-export-nightly
-- WARNING: contains credential material. Restricted distribution.

INSERT INTO accounts VALUES (1,'MFS-AC-1001','Harborline Trading','dokafor','customer');
INSERT INTO accounts VALUES (7,'MFS-SV-0007','Meridian Freight Solutions','svc_edi','service');
INSERT INTO accounts VALUES (11,'MFS-ST-0011','Meridian Freight Solutions','tbrandt','staff');
INSERT INTO accounts VALUES (12,'MFS-ST-0012','Meridian Freight Solutions','avoss','finance');
INSERT INTO accounts VALUES (13,'MFS-ST-0013','Meridian Freight Solutions','ops_console','operations');

-- Payroll run reference for this period
-- MERIDIAN{p4yr0ll_r3f_1n_n1ghtly_db_3xp0rt}
