#!/usr/bin/env python3
"""Regenerate every on-disk artifact from labsite/catalog.py.

Run after changing a proof value so the server-side files, the exposed backups
and the metadata service stay in sync with the catalogue.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from labsite.catalog import FINDINGS_BY_ID as F  # noqa: E402


def write(relative: str, content: str) -> None:
    path = ROOT / relative
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"wrote {relative}")


# --- instance/ : application secrets that live outside the document root ------
write("instance/app-secrets.ini", f"""\
; Meridian Freight Solutions - application secrets
; Managed by the platform team. Do not copy into the web root.
[session]
signing_key = meridian-default-signing-key
[integrations]
gateway_secret = mfs_gw_9f2ab71c
[recovery]
secrets_reference = {F['traversal-invoice']['flag']}
""")

write("instance/keys/depot-transfer.key", f"""\
# Depot file-transfer key, provisioned per environment.
# Consumed by the depot connectivity tooling on this host.
{F['rce-cmdi']['flag']}
""")

write("instance/keys/campaign-signing.key", f"""\
# Marketing campaign signing key (outbound email authenticity).
{F['rce-ssti']['flag']}
""")

write("instance/edi/partner-manifest.key", f"""\
# Supplier EDI manifest signing key.
{F['xxe-edi']['flag']}
""")

write("instance/README.txt",
      "Server-side configuration and key material for the Meridian application.\n"
      "Nothing in this directory is intended to be reachable over HTTP.\n")

# --- documents/ : the invoice store the portal serves from -------------------
write("documents/INV-2026-00841.txt",
      "MERIDIAN FREIGHT SOLUTIONS\nInvoice INV-2026-00841\n"
      "Account MFS-AC-1001 - Harborline Trading\n\n"
      "Sea LCL Rotterdam - Felixstowe      EUR 7,728.00\n"
      "Customs documentation                 EUR   145.00\n"
      "Total due                             EUR 7,873.00\n")
write("documents/INV-2026-00842.txt",
      "MERIDIAN FREIGHT SOLUTIONS\nInvoice INV-2026-00842\n"
      "Account MFS-AC-1002 - Northgate Components\n\n"
      "Road LTL Hamburg - Gdansk           EUR 2,365.00\n"
      "Total due                           EUR 2,365.00\n")
write("documents/terms-of-carriage.txt",
      "Meridian Freight Solutions - standard terms of carriage (extract).\n"
      "Liability is limited to the declared value of the consignment.\n")

# --- uploads/ : the applicant document store --------------------------------
write("uploads/README.txt",
      "Applicant document store. Files submitted through the careers page.\n")
write("uploads/hr-onboarding-pack-2026.txt", f"""\
MERIDIAN FREIGHT SOLUTIONS - INTERNAL
New starter onboarding pack, 2026 intake

Building access:      request via facilities, 3 working days
Payroll portal:       payroll.meridianfreight.example
IT service desk:      x4400
Onboarding reference: {F['upload-unrestricted']['flag']}

Do not circulate outside HR.
""")
write("uploads/cv-r-menon.txt",
      "Ravi Menon - logistics coordinator\nNorthgate Components, 2019-present\n")

# --- backups/ : the nightly export folder with autoindex on ------------------
write("backups/meridian-db-export.sql", f"""\
-- Meridian Freight Solutions nightly export
-- Generated by scheduled job mfs-export-nightly
-- WARNING: contains credential material. Restricted distribution.

INSERT INTO accounts VALUES (1,'MFS-AC-1001','Harborline Trading','dokafor','customer');
INSERT INTO accounts VALUES (7,'MFS-SV-0007','Meridian Freight Solutions','svc_edi','service');
INSERT INTO accounts VALUES (11,'MFS-ST-0011','Meridian Freight Solutions','tbrandt','staff');
INSERT INTO accounts VALUES (12,'MFS-ST-0012','Meridian Freight Solutions','avoss','finance');
INSERT INTO accounts VALUES (13,'MFS-ST-0013','Meridian Freight Solutions','ops_console','operations');

-- Payroll run reference for this period
-- {F['misconfig-backups']['flag']}
""")
write("backups/export-manifest.txt",
      "mfs-export-nightly\nlast run: 02:15 UTC\nretention: 14 days\n"
      "destination: //mfs-fs01/exports (pending migration to object storage)\n")

# --- internal/ : the runbook robots.txt points at ---------------------------
write("internal/it-runbook.txt", f"""\
MERIDIAN FREIGHT SOLUTIONS - IT OPERATIONS RUNBOOK (INTERNAL)
============================================================

Platform
  Web front end        IIS / reverse proxy to the application service
  Application service  127.0.0.1:5005
  Nightly export       /backups (autoindex still enabled - ticket OPS-4401)

Known issues
  OPS-4388  Portal sign-in still offers the pre-migration path (?legacy=1).
            That path was never converted to parameterised queries.
  OPS-4412  Depot connectivity check passes the host field to a shell.
  OPS-4455  Session signing key is still the packaged default. Rotation blocked
            on the partner gateway release.

Out-of-hours access
  Duty engineer escalation code: {F['recon-runbook']['flag']}
  Escalate to the on-call platform lead if the portal is unavailable > 15 min.
""")

# --- metadata service : SSRF target -----------------------------------------
write("metadata/index.html",
      "<h1>Instance metadata</h1><p>"
      '<a href="latest/meta-data/">latest/meta-data/</a></p>\n')
write("metadata/latest/meta-data/index.html",
      '<a href="iam/">iam/</a>\n<a href="hostname">hostname</a>\n')
write("metadata/latest/meta-data/hostname", "mfs-web-prod-01.meridianfreight.example\n")
write("metadata/latest/meta-data/iam/index.html",
      '<a href="security-credentials/">security-credentials/</a>\n')
write("metadata/latest/meta-data/iam/security-credentials/index.html",
      "mfs-web-instance-role\n")
write("metadata/latest/meta-data/iam/security-credentials/mfs-web-instance-role",
      json.dumps({
          "Code": "Success", "Type": "AWS-HMAC",
          "AccessKeyId": "AKIAMFSLABONLYNOTVALID",
          "SecretAccessKey": "lab/synthetic/secret/not-a-real-key",
          "Token": F["ssrf-metadata"]["flag"],
          "Expiration": "2099-01-01T00:00:00Z",
      }, indent=2) + "\n")
